import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import StoreProvider from "../StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_AUTH_CLIENT_ID}>
            {children}
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
